<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PiliticasTerminos extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        DB::table('politycs_conditions')->insert([
            [
                'title' => 'here', 
                'content' => '<p class="MsoNormal" style="text-align: center;" align="center"><strong><span lang="ES-PE" style="font-size: 18.0pt; line-height: 107%;">POLITICAS DE PRIVACIDAD</span></strong></p>
                <p class="MsoNormal"><span lang="ES-PE">&nbsp;</span></p>
                <p class="MsoNormal"><span lang="ES-PE">I.<span style="mso-spacerun: yes;">&nbsp;&nbsp;&nbsp;&nbsp; </span>OBJETIVO DE LA PRESENTE POL&Iacute;TICA</span></p>
                <p class="MsoNormal"><span lang="ES-PE">&nbsp;</span></p>
                <p class="MsoNormal"><span lang="ES-PE">La presente pol&iacute;tica tiene por objeto dar a conocer el modo en que PERU ANDES TOP E.I.R.L (en adelante &ldquo;Peru Andes Top&rdquo;) protege y trata los datos de car&aacute;cter personal de los clientes, pasajeros, proveedores, operadores de turismo, agencias de viajes y colaboradores, desde su recolecci&oacute;n a trav&eacute;s de los distintos canales, sean &eacute;stos f&iacute;sico o digitales, para los fines debidamente comunicados.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">&nbsp;</span></p>
                <p class="MsoNormal"><span lang="ES-PE">II.<span style="mso-spacerun: yes;">&nbsp;&nbsp;&nbsp;&nbsp; </span>INFORMACION GENERAL</span></p>
                <p class="MsoNormal"><span lang="ES-PE">&nbsp;</span></p>
                <p class="MsoNormal"><span lang="ES-PE">Peru Andes Top es una empresa que presta servicios de viajes individuales y colectivos, organiza tour y excursiones, conseguir alojamiento y ejercer cualquier otra actividad relacionada directamente con el turismo. Para tal fin se recolecta, utiliza, administra, transfiere, almacena y procesa informaci&oacute;n, que puede asociarse a informaci&oacute;n perteneciente a personas naturales en el desarrollo de sus actividades. Siendo, por ejemplo: nombre, documento de identidad, n&uacute;mero de tel&eacute;fono, direcci&oacute;n de correo electr&oacute;nico, pa&iacute;s de residencia, entre otros a trav&eacute;s de diversos formatos f&iacute;sicos y digitales.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">&nbsp;</span></p>
                <p class="MsoNormal"><span lang="ES-PE">Peru Andes Top, de conformidad con la Ley Peruana N&deg; 29733 &ndash; Ley de Protecci&oacute;n de Datos Personales &ndash; y su Reglamento N&deg; 003-2013-JUS; as&iacute; como del Reglamento General de Protecci&oacute;n de Datos GDPR (UE 2016/679), se compromete a garantizar y adoptar medidas para la seguridad de la informaci&oacute;n a trav&eacute;s de las mejores pr&aacute;cticas internacionales, en atenci&oacute;n a la confidencialidad, integridad y disponibilidad de los datos de car&aacute;cter personal facilitados.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">&nbsp;</span></p>
                <p class="MsoNormal"><span lang="ES-PE">III.<span style="mso-spacerun: yes;">&nbsp;&nbsp;&nbsp;&nbsp; </span>DEFINICIONES</span></p>
                <p class="MsoNormal"><span lang="ES-PE">&nbsp;</span></p>
                <p class="MsoNormal"><span lang="ES-PE">Responsable del tratamiento: es la persona f&iacute;sica o jur&iacute;dica que, solo o junto con otros, determina los fines y medios del tratamiento de datos de car&aacute;cter personal; es decir, Peru Andes Top ser&aacute; el responsable de los datos personales obtenidos a trav&eacute;s de sus diversos canales de recolecci&oacute;n y facilitados por los usuarios de Peru Andes Top.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">Datos de car&aacute;cter personal: es toda aquella informaci&oacute;n sobre una persona f&iacute;sica identificada o identificable (el usuario), como por ejemplo el nombre, DNI, pasaporte, datos de localizaci&oacute;n o uno o varios elementos propios de la identidad f&iacute;sica, fisiol&oacute;gica, gen&eacute;tica, ps&iacute;quica, econ&oacute;mica, cultural o social de una</span></p>
                <p class="MsoNormal"><span lang="ES-PE">Tratamiento: ser&iacute;a cualquier operaci&oacute;n o conjunto de operaciones realizadas sobre datos personales o conjuntos de datos personales (automatizados o no) como pueden ser la recogida, el registro, organizaci&oacute;n, modificaci&oacute;n, consulta, utilizaci&oacute;n, difusi&oacute;n o cualquier otra forma de habilitaci&oacute;n de acceso, cotejo o interconexi&oacute;n, limitaci&oacute;n, supresi&oacute;n o destrucci&oacute;n de datos de car&aacute;cter personal.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">Derecho de acceso: es el derecho del Usuario de conocer qu&eacute; datos est&aacute; tratando Peru Andes Top y obtener una copia de los mismos.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">Derecho de rectificaci&oacute;n: es el derecho del usuario de actualizar, rectificar y/o corregir sus datos datos personales.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">Derecho de oposici&oacute;n: es el derecho del usuario de oponerse en todo momento al tratamiento de sus datos personales por parte de Peru Andes Top.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">Derecho de cancelaci&oacute;n (&laquo;derecho al olvido&raquo;): es el derecho del usuario de solicitar la supresi&oacute;n de sus datos en cualquier documento, archivo o lugar en el que &eacute;stos est&eacute;n accesibles.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">Derecho de limitaci&oacute;n del tratamiento: es el derecho del usuario de exigir que se limite el tratamiento de sus datos cuando se produzca alguna de las circunstancias establecidas en la legislaci&oacute;n, como pueden ser el tratamiento il&iacute;cito de los datos o que Peru Andes Top ya no los necesite. </span></p>
                <p class="MsoNormal"><span lang="ES-PE">Derecho a la portabilidad de los datos: es el derecho del usuario de recibir los datos personales que le incumban, que haya facilitado a Peru Andes Top, en un formato estructurado, de uso com&uacute;n y lectura mec&aacute;nica, y a transmitirlos a otro responsable del tratamiento sin que pueda impedirlo. </span></p>
                <p class="MsoNormal"><span lang="ES-PE">Derecho a no ser objeto de decisiones individualizadas: es el derecho del usuario a no ser objeto de una decisi&oacute;n basada &uacute;nicamente en el tratamiento automatizado, incluida la elaboraci&oacute;n de perfiles, que produzca efectos jur&iacute;dicos en &eacute;l o le afecte significativamente de modo similar.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">IV.<span style="mso-spacerun: yes;">&nbsp;&nbsp;&nbsp;&nbsp; </span>CONSENTIMIENTO Y LEGITIMIZACI&Oacute;N DEL TRATAMIENTO</span></p>
                <p class="MsoNormal"><span lang="ES-PE">&nbsp;</span></p>
                <p class="MsoNormal"><span lang="ES-PE">Peru Andes Top trata los datos de los usuarios:</span></p>
                <p class="MsoNormal"><span lang="ES-PE">&nbsp;</span></p>
                <p class="MsoNormal"><span lang="ES-PE">(i)<span style="mso-spacerun: yes;">&nbsp;&nbsp;&nbsp; </span>Cuando estos dan su consentimiento expresamente para el tratamiento de sus datos personales para las finalidades detalladas en este documento.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">&nbsp;</span></p>
                <p class="MsoNormal"><span lang="ES-PE">(ii)<span style="mso-spacerun: yes;">&nbsp;&nbsp; </span>Cuando el tratamiento es necesario para la ejecuci&oacute;n de un contrato de prestaci&oacute;n de servicios y productos en el que el usuario es parte.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">&nbsp;</span></p>
                <p class="MsoNormal"><span lang="ES-PE">V.<span style="mso-spacerun: yes;">&nbsp;&nbsp;&nbsp;&nbsp; </span>DATOS PERSONALES OBJETO DE TRATAMIENTO Y ALCANCE</span></p>
                <p class="MsoNormal"><span lang="ES-PE">&nbsp;</span></p>
                <p class="MsoNormal"><span lang="ES-PE">La presente pol&iacute;tica est&aacute; dirigida a los datos personales correspondientes a los clientes, pasajeros, proveedores, operadores de turismo, agencias de viajes y colaboradores, suministrados por ellos mismos, haciendo uso de su libertad, de manera voluntaria y consciente. La informaci&oacute;n recolectada y almacenada comprende datos b&aacute;sicos ingresados mediante formularios de registro, de contacto u otros similares; como pueden ser, por ejemplo, nombre, DNI, pasaporte, g&eacute;nero, edad, n&uacute;mero de tel&eacute;fono, direcci&oacute;n de correo electr&oacute;nico, pa&iacute;s de residencia, entre otros, datos recogidos a trav&eacute;s los diversos canales que la empresa gestiona, necesarios para la prestaci&oacute;n de los servicios tur&iacute;sticos de Peru Andes Top.<span style="mso-spacerun: yes;">&nbsp; </span>En cualquier caso, los usuarios podr&aacute;n ver cu&aacute;les son esenciales para la correcta prestaci&oacute;n del servicio y cuales tendr&aacute;n car&aacute;cter accesorio antes de enviar sus datos personales.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">&nbsp;</span></p>
                <p class="MsoNormal"><span lang="ES-PE">El usuario ser&aacute; el &uacute;nico responsable de la veracidad y exactitud de los datos aportados. S&oacute;lo podr&aacute;n ser usuarios los mayores de 18 a&ntilde;os y/o aquellos con capacidad jur&iacute;dica suficiente. Asimismo, el usuario ser&aacute; el &uacute;nico responsable en cuanto a los datos aportados de terceros, as&iacute; como de garantizar haberles informado de la presente Pol&iacute;tica de Privacidad y haber obtenido su consentimiento expreso.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">&nbsp;</span></p>
                <p class="MsoNormal"><span lang="ES-PE">VI.<span style="mso-spacerun: yes;">&nbsp;&nbsp;&nbsp;&nbsp; </span>PRINCIPIOS RECTORES</span></p>
                <p class="MsoNormal"><span lang="ES-PE">&nbsp;</span></p>
                <p class="MsoNormal"><span lang="ES-PE">Peru Andes Top tendr&aacute;n en cuenta los siguientes principios en el proceso de tratamiento de los datos personales.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">&nbsp;</span></p>
                <p class="MsoNormal"><span lang="ES-PE">a.<span style="mso-spacerun: yes;">&nbsp;&nbsp;&nbsp;&nbsp; </span>Principio de Legalidad: El tratamiento de datos personales en t&eacute;rminos de la Ley 29733 es una actividad reglada que debe sujetarse a lo establecido en la citada norma, y en las dem&aacute;s disposiciones que la reglamenten. Se proh&iacute;be la recopilaci&oacute;n de los datos personales por medios fraudulentos, desleales o il&iacute;citos.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">&nbsp;</span></p>
                <p class="MsoNormal"><span lang="ES-PE">b.<span style="mso-spacerun: yes;">&nbsp;&nbsp;&nbsp;&nbsp; </span>Principio de Consentimiento: En atenci&oacute;n al principio de consentimiento, el tratamiento de los datos personales es l&iacute;cito cuando el titular del dato personal hubiera prestado su consentimiento libre, previo, expreso, informado e inequ&iacute;voco. No se admiten f&oacute;rmulas de consentimiento en las que &eacute;ste no sea expresado de forma directa, como aquellas en las que se requiere presumir, o asumir la existencia de una voluntad que no ha sido expresa. Incluso el consentimiento prestado con otras declaraciones, deber&aacute; manifestarse en forma expresa y</span></p>
                <p class="MsoNormal"><span lang="ES-PE">&nbsp;</span></p>
                <p class="MsoNormal"><span lang="ES-PE">c.<span style="mso-spacerun: yes;">&nbsp;&nbsp;&nbsp;&nbsp; </span>Principio de Finalidad: En atenci&oacute;n al principio de finalidad se considera que una finalidad est&aacute; determinada cuando haya sido expresada con claridad, sin lugar a confusi&oacute;n y cuando de manera objetiva se especifica el objeto que tendr&aacute; el tratamiento de los datos personales. Trat&aacute;ndose de banco de datos personales que contengan datos sensibles, su creaci&oacute;n solo puede justificarse si su finalidad adem&aacute;s de ser leg&iacute;tima, es concreta y acorde con las actividades o fines expl&iacute;citos del titular del banco de datos Los profesionales que realicen el tratamiento de alg&uacute;n dato personal, adem&aacute;s de estar limitados por la finalidad de sus servicios, se encuentran obligados a guardar secreto profesional.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">&nbsp;</span></p>
                <p class="MsoNormal"><span lang="ES-PE">d.<span style="mso-spacerun: yes;">&nbsp;&nbsp;&nbsp; </span>Principio de Calidad: Los datos personales que vayan a ser tratados deben ser veraces, exactos y, en la medida de lo posible, actualizados, necesarios, pertinentes y adecuados respecto de la finalidad para la que fueron recopilados. Deben conservarse de forma tal que se garantice su seguridad y solo por el tiempo necesario para cumplir con la finalidad del tratamiento.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">&nbsp;</span></p>
                <p class="MsoNormal"><span lang="ES-PE">e.<span style="mso-spacerun: yes;">&nbsp;&nbsp;&nbsp;&nbsp; </span>Principio de Proporcionalidad: Todo tratamiento de datos personales debe ser adecuado, relevante y no excesivo a la finalidad para que estos hubiesen sido recopilados.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">&nbsp;</span></p>
                <p class="MsoNormal"><span lang="ES-PE">f.<span style="mso-spacerun: yes;">&nbsp;&nbsp;&nbsp;&nbsp; </span>Principio de Seguridad: El titular del banco de datos personales y el encargado de su tratamiento deben adoptar las medidas t&eacute;cnicas, organizativas y legales necesarias para garantizar la seguridad de los datos personales. Las medidas de seguridad deben ser apropiadas y acordes con el tratamiento que se vaya a efectuar y con la categor&iacute;a de datos personales de que se trate.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">&nbsp;</span></p>
                <p class="MsoNormal"><span lang="ES-PE">g.<span style="mso-spacerun: yes;">&nbsp;&nbsp;&nbsp;&nbsp; </span>Principio de Disposici&oacute;n de Recurso: Todo titular de datos personales debe contar con las v&iacute;as administrativas o jurisdiccionales necesarias para reclamar y hacer valer sus derechos, cuando estos sean vulnerados por el tratamiento de sus datos personales.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">&nbsp;</span></p>
                <p class="MsoNormal"><span lang="ES-PE">h.<span style="mso-spacerun: yes;">&nbsp;&nbsp;&nbsp;&nbsp; </span>Principio de Nivel de Protecci&oacute;n Adecuado: Para el flujo fronterizo de datos personales, se debe garantizar un nivel suficiente de protecci&oacute;n para los datos personales que se vayan a tratar o, por lo menos, equiparable a lo previsto por la Ley o por est&aacute;ndares internacionales en la materia.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">&nbsp;</span></p>
                <p class="MsoNormal"><span lang="ES-PE">VII.<span style="mso-spacerun: yes;">&nbsp;&nbsp;&nbsp;&nbsp; </span>FINALIDADES DE LOS DATOS PERSONALES</span></p>
                <p class="MsoNormal"><span lang="ES-PE">&nbsp;</span></p>
                <p class="MsoNormal"><span lang="ES-PE">Peru Andes Top utilizar&aacute; los datos personales proporcionados por los usuarios para las siguientes finalidades:</span></p>
                <p class="MsoNormal"><span lang="ES-PE">&nbsp;</span></p>
                <p class="MsoNormal"><span lang="ES-PE">Pasajeros:</span></p>
                <p class="MsoNormal"><span lang="ES-PE">&nbsp;</span></p>
                <p class="MsoNormal"><span lang="ES-PE">Cumplir con el objetivo de la prestaci&oacute;n de los servicios y productos tur&iacute;sticos contratados.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">Contactar con el cliente (agencias de viaje, empresas y persona natural) durante la prestaci&oacute;n de los servicios y productos contratados.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">Facilitar la coordinaci&oacute;n con proveedores, agencias de viaje, y hoteles.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">Remitir a los clientes informaci&oacute;n relativa a la naturaleza del servicio y/o disposiciones de obligatorio conocimiento y cumplimiento durante el servicio, por ejemplo, las condiciones de contrataci&oacute;n, cumplimientos tributarios y/u otras condiciones dentro de las que podr&iacute;an incluirse pol&iacute;ticas internas de la empresa.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">Para responder a las dudas, consultas y solicitudes.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">Sustentar las liquidaciones del Impuesto al Valor Agregado No Domiciliado ante las Autoridades Tributarias, a trav&eacute;s de la informaci&oacute;n de Pasaporte y Tarjeta Andina de Migraciones (TAM), entre otros.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">Analizar e identificar las expectativas y preferencias de las agencias de viajes para adquirir boletos y servicios.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">Trabajadores y colaboradores:</span></p>
                <p class="MsoNormal"><span lang="ES-PE">&nbsp;</span></p>
                <p class="MsoNormal"><span lang="ES-PE">La empresa, solicitar&aacute; a sus trabajadores informaci&oacute;n personal para cumplir con los requerimientos normativos laborales vigentes y/o el desarrollo de proyectos relacionados a Recursos Humanos y Gesti&oacute;n del Talento como registro de n&oacute;minas, asistencia de personal, selecci&oacute;n de personal, pago de comisiones, entre otros.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">Seguridad en las instalaciones a trav&eacute;s de la video vigilancia.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">Cumplir con la pol&iacute;tica y los procedimientos de la Pol&iacute;tica de Prevenci&oacute;n de Lavado de Activos y Financiamiento del terrorismo. </span></p>
                <p class="MsoNormal"><span lang="ES-PE">Operadores de Turismo y Proveedores:</span></p>
                <p class="MsoNormal"><span lang="ES-PE">&nbsp;</span></p>
                <p class="MsoNormal"><span lang="ES-PE">Poder gestionar el pago de los servicios y productos solicitados.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">Para contactar sobre la prestaci&oacute;n de los servicios y productos contratados.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">Seguridad en las instalaciones a trav&eacute;s de la video vigilancia.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">VIII.<span style="mso-spacerun: yes;">&nbsp;&nbsp;&nbsp;&nbsp; </span>DERECHOS DE LOS TITULARES</span></p>
                <p class="MsoNormal"><span lang="ES-PE"><span style="mso-spacerun: yes;">&nbsp;</span></span></p>
                <p class="MsoNormal"><span lang="ES-PE">El titular de los datos personales tendr&aacute; los siguientes derechos:</span></p>
                <p class="MsoNormal"><span lang="ES-PE">&nbsp;</span></p>
                <p class="MsoNormal"><span lang="ES-PE">a.<span style="mso-spacerun: yes;">&nbsp;&nbsp;&nbsp;&nbsp; </span>Los derechos de informaci&oacute;n, acceso, rectificaci&oacute;n, cancelaci&oacute;n, oposici&oacute;n y tratamiento objetivo de datos personales s&oacute;lo pueden ser ejercidos por el titular de datos personales, sin perjuicio de las normas que regulan la representaci&oacute;n.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">&nbsp;</span></p>
                <p class="MsoNormal"><span lang="ES-PE">b.<span style="mso-spacerun: yes;">&nbsp;&nbsp;&nbsp;&nbsp; </span>El ejercicio de alguno o algunos de los derechos no excluye la posibilidad de ejercer alguno o algunos de los otros, ni puede ser entendido como requisito previo para el ejercicio de cualquiera de ellos.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">&nbsp;</span></p>
                <p class="MsoNormal"><span lang="ES-PE">c.<span style="mso-spacerun: yes;">&nbsp;&nbsp;&nbsp;&nbsp; </span>Conocer, actualizar y rectificar sus datos personales frente a Peru Andes Top o frente al encargado del tratamiento designado. Este derecho se podr&aacute; ejercer, entre otros frente a datos parciales, inexactos, incompletos, fraccionados, que induzcan a error, o aquellos cuyo tratamiento est&eacute; expresamente prohibido o no haya sido autorizado.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">&nbsp;</span></p>
                <p class="MsoNormal"><span lang="ES-PE">d.<span style="mso-spacerun: yes;">&nbsp;&nbsp;&nbsp;&nbsp; </span>Ser informado por parte de Peru Andes Top o por parte del encargado del tratamiento designado, previa solicitud, respecto del uso que les ha dado a sus datos personales.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">&nbsp;</span></p>
                <p class="MsoNormal"><span lang="ES-PE">e.<span style="mso-spacerun: yes;">&nbsp;&nbsp;&nbsp;&nbsp; </span>Revocar la autorizaci&oacute;n y/o solicitar la supresi&oacute;n del dato cuando en el tratamiento no se respeten los principios, derechos y garant&iacute;as constitucionales y legales. La revocatoria y/o supresi&oacute;n proceder&aacute; cuando la Autoridad Nacional de Protecci&oacute;n de Datos Personales haya determinado que en el tratamiento Peru Andes Top o el encargado del tratamiento designado, han incurrido en conductas contrarias a la Ley 29733 y la Constituci&oacute;n.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">&nbsp;</span></p>
                <p class="MsoNormal"><span lang="ES-PE">f.<span style="mso-spacerun: yes;">&nbsp;&nbsp;&nbsp;&nbsp; </span>Acceder en forma gratuita en las condiciones definidas en este documento, a sus datos personales que hayan sido objeto de tratamiento.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">&nbsp;</span></p>
                <p class="MsoNormal"><span lang="ES-PE">IX.<span style="mso-spacerun: yes;">&nbsp;&nbsp;&nbsp;&nbsp; </span>CONDICIONES PARA EL TRATAMIENTO DE DATOS</span></p>
                <p class="MsoNormal"><span lang="ES-PE">&nbsp;</span></p>
                <p class="MsoNormal"><span lang="ES-PE">a.<span style="mso-spacerun: yes;">&nbsp;&nbsp;&nbsp;&nbsp; </span>Autorizaci&oacute;n del Titular:</span></p>
                <p class="MsoNormal"><span lang="ES-PE">&nbsp;</span></p>
                <p class="MsoNormal"><span lang="ES-PE">Para que Peru Andes Top realice cualquier acci&oacute;n de tratamiento de datos personales, se requiere la autorizaci&oacute;n previa e informada del titular, la cual deber&aacute; ser obtenida por cualquier medio que pueda ser objeto de consulta posterior. Estos mecanismos podr&aacute;n ser predeterminados a trav&eacute;s de medios t&eacute;cnicos que faciliten al titular su manifestaci&oacute;n automatizada o pueden ser por escrito o de forma oral. Peru Andes Top adoptar&aacute; los procedimientos necesarios para solicitar, a m&aacute;s tardar en el momento de recolecci&oacute;n de los datos, la autorizaci&oacute;n del Titular para el tratamiento de los mismos e informar&aacute; los datos personales que ser&aacute;n recolectados, as&iacute; como todas las finalidades espec&iacute;ficas del tratamiento para los cuales se obtiene el consentimiento.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">&nbsp;</span></p>
                <p class="MsoNormal"><span lang="ES-PE">Los datos personales que se encuentren en fuentes de acceso p&uacute;blico, podr&aacute;n ser tratados por Peru Andes Top siempre y cuando sean por naturaleza datos p&uacute;blicos. En caso de realizarse cambios sustanciales en el contenido de las pol&iacute;ticas de tratamiento de<span style="mso-spacerun: yes;">&nbsp;&nbsp; </span>datos de<span style="mso-spacerun: yes;">&nbsp;&nbsp; </span>Peru Andes Top,<span style="mso-spacerun: yes;">&nbsp;&nbsp; </span>en relaci&oacute;n con la<span style="mso-spacerun: yes;">&nbsp;&nbsp; </span>identificaci&oacute;n del responsable y a la finalidad del tratamiento de los datos personales, los cuales afecten el contenido de la autorizaci&oacute;n, Peru Andes Top comunicar&aacute; estos cambios a los titulares, antes o m&aacute;s tardar al momento de implementar las nuevas pol&iacute;ticas, adem&aacute;s obtendr&aacute; del Titular una nueva autorizaci&oacute;n cuando el cambio se refiera a la finalidad del tratamiento. Para la comunicaci&oacute;n de los cambios y la autorizaci&oacute;n se podr&aacute;n utilizar medios t&eacute;cnicos que faciliten dicha actividad.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">&nbsp;</span></p>
                <p class="MsoNormal"><span lang="ES-PE">b.<span style="mso-spacerun: yes;">&nbsp;&nbsp;&nbsp;&nbsp; </span>Casos en que no es necesaria la autorizaci&oacute;n:</span></p>
                <p class="MsoNormal"><span lang="ES-PE">&nbsp;</span></p>
                <p class="MsoNormal"><span lang="ES-PE">Informaci&oacute;n requerida por una entidad p&uacute;blica o administrativa en ejercicio de sus funciones legales o por orden judicial.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">Datos de naturaleza p&uacute;blica.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">Casos de urgencia m&eacute;dica o sanitario.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">Tratamiento de informaci&oacute;n autorizado por la Ley para fines hist&oacute;ricos, estad&iacute;sticos o cient&iacute;ficos.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">Datos relacionados con el Registro Civil de las personas.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">c.<span style="mso-spacerun: yes;">&nbsp;&nbsp;&nbsp;&nbsp; </span>Suministro de la Informaci&oacute;n:</span></p>
                <p class="MsoNormal"><span lang="ES-PE">&nbsp;</span></p>
                <p class="MsoNormal"><span lang="ES-PE">La informaci&oacute;n solicitada por el titular ser&aacute; suministrada por Peru Andes Top del mismo modo como fue formulada la solicitud.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">&nbsp;</span></p>
                <p class="MsoNormal"><span lang="ES-PE">d.<span style="mso-spacerun: yes;">&nbsp;&nbsp;&nbsp;&nbsp; </span>Deber de Informar al Titular.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">&nbsp;</span></p>
                <p class="MsoNormal"><span lang="ES-PE">Peru Andes Top, al momento de solicitar al titular la autorizaci&oacute;n, deber&aacute; informarle de manera clara y expresa lo siguiente:</span></p>
                <p class="MsoNormal"><span lang="ES-PE">&nbsp;</span></p>
                <p class="MsoNormal"><span lang="ES-PE">El tratamiento al cual ser&aacute;n sometidos sus datos personales y la finalidad del mismo.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">El car&aacute;cter facultativo de la respuesta a las preguntas que le sean hechas, cuando estas versen sobre datos sensibles o sobre los datos de las ni&ntilde;as, ni&ntilde;os y adolescentes. </span></p>
                <p class="MsoNormal"><span lang="ES-PE">Los derechos que le asisten como titular.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">La identificaci&oacute;n, direcci&oacute;n f&iacute;sica o electr&oacute;nica y tel&eacute;fono del responsable del tratamiento.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">e.<span style="mso-spacerun: yes;">&nbsp;&nbsp;&nbsp;&nbsp; </span>Revocatoria de la autorizaci&oacute;n y/o supresi&oacute;n de datos:</span></p>
                <p class="MsoNormal"><span lang="ES-PE">&nbsp;</span></p>
                <p class="MsoNormal"><span lang="ES-PE">Los titulares podr&aacute;n en todo momento solicitar a Peru Andes Top, la supresi&oacute;n de sus datos personales y/o revocar la autorizaci&oacute;n otorgada para el tratamiento de los mismos, mediante la presentaci&oacute;n de una solicitud, conforme a lo establecido la Ley 29733 de 2011 y el reglamento DS No. 003-2013-JUS de 2013.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">&nbsp;</span></p>
                <p class="MsoNormal"><span lang="ES-PE">La solicitud de supresi&oacute;n de la informaci&oacute;n y la revocatoria de la autorizaci&oacute;n no proceder&aacute;n cuando el titular tenga un deber contractual de permanecer en la base de datos de Peru Andes Top</span></p>
                <p class="MsoNormal"><span lang="ES-PE">f.<span style="mso-spacerun: yes;">&nbsp;&nbsp;&nbsp;&nbsp; </span>Personas a quienes se les puede suministrar la informaci&oacute;n:</span></p>
                <p class="MsoNormal"><span lang="ES-PE">&nbsp;</span></p>
                <p class="MsoNormal"><span lang="ES-PE">La informaci&oacute;n acerca de los datos personales que hayan sido materia de tratamiento por parte de Peru Andes Top podr&aacute; suministrarse a las</span></p>
                <p class="MsoNormal"><span lang="ES-PE">&nbsp;</span></p>
                <p class="MsoNormal"><span lang="ES-PE">A los titulares, sus causahabientes o sus representantes legales.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">A las entidades p&uacute;blicas o administrativas en ejercicio de sus funciones legales o por orden judicial.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">A los terceros autorizados por el titular o por la ley.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">X<span style="mso-spacerun: yes;">&nbsp;&nbsp;&nbsp;&nbsp; </span>SEGURIDAD DE LOS DATOS PERSONALES</span></p>
                <p class="MsoNormal"><span lang="ES-PE">&nbsp;</span></p>
                <p class="MsoNormal"><span lang="ES-PE">Peru Andes Top cumple con las medidas de protecci&oacute;n de datos de car&aacute;cter personal legalmente requeridas y ha adoptado las medidas razonablemente exigibles conforme a los conocimientos t&eacute;cnicos actuales y buenas pr&aacute;cticas para la custodia y gesti&oacute;n de la informaci&oacute;n a fin de evitar la p&eacute;rdida, mal uso, alteraci&oacute;n, intrusi&oacute;n ileg&iacute;tima y sustracci&oacute;n de los datos de car&aacute;cter personal que facilitan los usuarios.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">&nbsp;</span></p>
                <p class="MsoNormal"><span lang="ES-PE">XI PROCEDIMIENTOS</span></p>
                <p class="MsoNormal"><span lang="ES-PE">&nbsp;</span></p>
                <p class="MsoNormal"><span lang="ES-PE">El titular o sus causahabientes tienen derecho a presentar ante Peru Andes Top, consultas y/o reclamaciones, previa verificaci&oacute;n de su identidad, a trav&eacute;s de un medio escrito dirigido a la siguiente direcci&oacute;n en cualquier momento, retirar su consentimiento para el tratamiento de los datos de car&aacute;cter personal y/o podr&aacute; ejercer sus derechos de acceso, informaci&oacute;n, rectificaci&oacute;n, oposici&oacute;n, supresi&oacute;n, limitaci&oacute;n, olvido, portabilidad y a no ser objeto de decisiones individualizadas, dirigi&eacute;ndose mediante un escrito dirigido al Peru Andes Top con la referencia &laquo;DATOS PERSONALES&raquo; a las siguientes direcciones:</span></p>
                <p class="MsoNormal"><span lang="ES-PE">&nbsp;</span></p>
                <p class="MsoNormal"><span lang="ES-PE">Direcci&oacute;n F&iacute;sical: Urb. San Borja Jr. Ancash Mz. B Lote 20 </span></p>
                <p class="MsoNormal"><span lang="ES-PE">E-mail: gettripgroup@gmail.com</span></p>
                <p class="MsoNormal"><span lang="ES-PE">Peru Andes Top responder&aacute; la consulta y/o reclamaci&oacute;n por el mismo medio que fue formulada:</span></p>
                <p class="MsoNormal"><span lang="ES-PE">&nbsp;</span></p>
                <p class="MsoNormal"><span lang="ES-PE">a)<span style="mso-spacerun: yes;">&nbsp;&nbsp;&nbsp;&nbsp; </span>CONSULTAS (ACCESO/INFORMACI&Oacute;N)</span></p>
                <p class="MsoNormal"><span lang="ES-PE">&nbsp;</span></p>
                <p class="MsoNormal"><span lang="ES-PE">Los Titulares o sus causahabientes podr&aacute;n consultar la informaci&oacute;n personal del Titular que repose en la base de datos de Peru Andes Top, quien suministrar&aacute; al solicitante toda la informaci&oacute;n contenida en sus bases de datos, vinculada con la identificaci&oacute;n del Titular.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">&nbsp;</span></p>
                <p class="MsoNormal"><span lang="ES-PE">El titular podr&aacute; consultar de forma gratuita sus datos personales cada vez que existan modificaciones sustanciales a las Pol&iacute;ticas de Tratamiento de Datos de Peru Andes Top.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">&nbsp;</span></p>
                <p class="MsoNormal"><span lang="ES-PE">Toda consulta se responder&aacute; por el mismo medio que fue formulada dentro de los 05 d&iacute;as h&aacute;biles siguientes a su presentaci&oacute;n. Para el cumplimiento de este derecho, el Titular o sus causahabientes deber&aacute;n de presentar el formulario de Acceso, el cual se encuentra en el Anexo de la presente pol&iacute;tica.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">&nbsp;</span></p>
                <p class="MsoNormal"><span lang="ES-PE">b)<span style="mso-spacerun: yes;">&nbsp;&nbsp;&nbsp;&nbsp; </span>RECLAMOS (SOLICITIDES / PETICIONES)</span></p>
                <p class="MsoNormal"><span lang="ES-PE">&nbsp;</span></p>
                <p class="MsoNormal"><span lang="ES-PE">El Titular o sus causahabientes que consideren que la informaci&oacute;n contenida en una base de datos debe ser objeto de rectificaci&oacute;n, cancelaci&oacute;n u oposici&oacute;n, o cuando adviertan el presunto incumplimiento de cualquiera de los deberes contenidos en la Ley 29733 de 2011, podr&aacute;n presentar una solicitud al Titular del Banco de Datos Personales o al responsable del Tratamiento de Peru Andes Top. Para el cumplimiento de estos derechos, el Titular o sus causahabientes deber&aacute;n de presentar el formulario respectivo, el cual se encuentra en el Anexo de la presente pol&iacute;tica.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">&nbsp;</span></p>
                <p class="MsoNormal"><span lang="ES-PE">XII DEBERES DE GETTRIP VACATION EN EL TRATAMIENTO DE DATOS</span></p>
                <p class="MsoNormal"><span lang="ES-PE">&nbsp;</span></p>
                <p class="MsoNormal"><span lang="ES-PE">Garantizar al Titular, en todo tiempo, el pleno y efectivo ejercicio del derecho de h&aacute;beas data.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">Solicitar y conservar, en las condiciones previstas en la Ley, copia de la respectiva autorizaci&oacute;n otorgada por el titular.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">Informar debidamente al Titular sobre la finalidad de la recolecci&oacute;n y los derechos que le asisten por virtud de la autorizaci&oacute;n otorgada.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">Tomar las medidas orientadas a conservar la informaci&oacute;n bajo las condiciones de seguridad para impedir su adulteraci&oacute;n, p&eacute;rdida, consulta, uso o acceso no autorizado o fraudulento.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">Tomar las medidas para que la informaci&oacute;n que se suministre al Encargado del Tratamiento sea veraz, completa, exacta, actualizada, comprobable y compresible. </span></p>
                <p class="MsoNormal"><span lang="ES-PE">Actualizar la informaci&oacute;n, comunicando de forma oportuna al Encargado del Tratamiento, todas las novedades respecto de los datos que previamente le haya suministrado y adoptar las dem&aacute;s medidas necesarias para que la informaci&oacute;n suministrada a este se mantenga actualizada.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">Rectificar la informaci&oacute;n cuando sea incorrecta y comunicar lo pertinente al Encargado del tratamiento.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">Suministrar al Encargado del Tratamiento, seg&uacute;n el caso, &uacute;nicamente datos cuyo Tratamiento est&eacute; previamente autorizado de conformidad con lo previsto en la ley.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">Exigir al Encargado del Tratamiento en todo momento, el respeto a las condiciones de seguridad y privacidad de la informaci&oacute;n del titular.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">Tramitar las consultas y reclamos formulados en los t&eacute;rminos se&ntilde;alados en la ley.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">Adoptar un manual interno de pol&iacute;ticas y procedimientos para garantizar el adecuado cumplimiento de la presente ley y en especial, para la atenci&oacute;n de consultas y reclamos.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">Informar al Encargado del Tratamiento cuando determinada informaci&oacute;n se encuentra en discusi&oacute;n por parte del Titular, una vez se haya presentado el reclamo y no haya finalizado el tr&aacute;mite respectivo.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">Informar a solicitud del Titular sobre el uso dado a sus datos.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">Informar a la Autoridad Nacional de Protecci&oacute;n de Datos Personales cuando se presenten violaciones a las pol&iacute;ticas de seguridad y existan riesgos en la administraci&oacute;n de la informaci&oacute;n de los titulares. </span></p>
                <p class="MsoNormal"><span lang="ES-PE">Cumplir las instrucciones y requerimientos que imparta la Autoridad Nacional de Protecci&oacute;n de Datos Personales.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">XIII<span style="mso-spacerun: yes;">&nbsp;&nbsp;&nbsp;&nbsp; </span>MEDIDADAS DE SEGURIDAD</span></p>
                <p class="MsoNormal"><span lang="ES-PE">&nbsp;</span></p>
                <p class="MsoNormal"><span lang="ES-PE">Peru Andes Top toma todas las precauciones razonables y medidas de &iacute;ndole t&eacute;cnico, administrativo y organizacional a fin de garantizar la seguridad de los datos de car&aacute;cter personal de los Titulares, principalmente aquellos destinados a impedir su alteraci&oacute;n, perdida y tratamiento o acceso no autorizado.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">&nbsp;</span></p>
                <p class="MsoNormal"><span lang="ES-PE">La aplicaci&oacute;n de las medidas de seguridad tiene como fin procurar la conservaci&oacute;n, confidencialidad, integridad, y disponibilidad de los datos.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">&nbsp;</span></p>
                <p class="MsoNormal"><span lang="ES-PE">Los lineamientos de seguridad de Peru Andes Top se encuentran respaldados por las pol&iacute;ticas de seguridad de la informaci&oacute;n de Peru Andes Top construidas bajo las mejores pr&aacute;cticas y est&aacute;ndares de seguridad existentes y dando cumplimiento a las regulaciones vigentes.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">&nbsp;</span></p>
                <p class="MsoNormal"><span lang="ES-PE">Dichas pol&iacute;ticas son de estricto cumplimiento por los funcionarios directos e indirectos que desempe&ntilde;an labores al interior de Peru Andes Top.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">&nbsp;</span></p>
                <p class="MsoNormal"><span lang="ES-PE">XV<span style="mso-spacerun: yes;">&nbsp;&nbsp;&nbsp;&nbsp; </span>CONCERVACI&Oacute;N DE LOS DATOS.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">&nbsp;</span></p>
                <p class="MsoNormal"><span lang="ES-PE">Los per&iacute;odos de conservaci&oacute;n de los datos personales de los usuarios por parte de Peru Andes Top ser&aacute;n diferentes en funci&oacute;n de la finalidad del tratamiento, por ello los datos ser&aacute;n conservados mientras est&eacute; vigente una relaci&oacute;n contractual para la prestaci&oacute;n de productos y servicios entre las empresas de Peru Andes Top y los usuarios y/o mientras los usuarios no soliciten la eliminaci&oacute;n de los datos personales a Peru Andes Top. Asimismo, los usuarios entienden y aceptan que ciertos datos de car&aacute;cter personal deber&aacute;n ser conservados por Peru Andes Top por normatividad legal y seg&uacute;n plazos establecidos en la legislaci&oacute;n.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">&nbsp;</span></p>
                <p class="MsoNormal"><span lang="ES-PE">XVI<span style="mso-spacerun: yes;">&nbsp;&nbsp;&nbsp;&nbsp; </span>MODIFICACIONES EN LA POLITICA</span></p>
                <p class="MsoNormal"><span lang="ES-PE">&nbsp;</span></p>
                <p class="MsoNormal"><span lang="ES-PE">Peru Andes Top podr&aacute; realizar cambios y actualizar la presente pol&iacute;tica en funci&oacute;n de novedades o exigencias legislativas, jurisprudenciales y/o por necesidades de la instituci&oacute;n, entre otras; por ello se recomienda a los usuarios que revisen esta pol&iacute;tica regularmente y/o cada vez que accedan al sitio web de la empresa.</span></p>',
                'finaltitle' => 'here'
            ]
            // Agrega más datos si es necesario
        ]);
        DB::table('terms_conditions')->insert([
            [
                'title' => 'here', 
                'content' => '<p class="MsoNormal" style="text-align: center;" align="center"><strong><span lang="ES-PE" style="font-size: 16.0pt; line-height: 107%;">TERMINOS Y CONDICIONES</span></strong></p>
                <p class="MsoNormal"><span lang="ES-PE">EL CLIENTE reconoce que la sociedad denominada &ldquo;PERU ANDES TOP GRUPO PATH OF THE ANDES EMPRESA INDIVIDUAL DE RESPONSABILIDAD LIMITADA&rdquo;, (en lo sucesivo PERU ANDES TOP) act&uacute;a como comercializadora de servicios tur&iacute;sticos nacionales y del extranjero, as&iacute; como intermediaria entre usuarios-turistas y de otros prestadores de servicios tur&iacute;sticos entre s&iacute;, tambi&eacute;n respecto de la comercializaci&oacute;n de paquetes tur&iacute;sticos, servicios tur&iacute;sticos, paquetes de viajes a trav&eacute;s de medios electr&oacute;nicos, portales digitales, p&aacute;ginas web, &ldquo;e-commerce&rdquo; (tiendas en l&iacute;nea o internet), realizar reservaciones, integraci&oacute;n, desarrollo, operaci&oacute;n y compraventa de paquetes tur&iacute;sticos, tanto de transporte a&eacute;reo, terrestre, mar&iacute;timo por cuenta propia o de terceros, al igual presta el servicio a los usuarios-turistas servicios de orientaci&oacute;n, asesor&iacute;a, reservaci&oacute;n y adquisici&oacute;n de boletos, billetes, tickets, pases, o entradas para espect&aacute;culos p&uacute;blicos o privados, nacionales o en el extranjero, los cuales estar&aacute;n sujetos a los t&eacute;rminos y condiciones especificados por los prestadores de servicios contratados, incluyendo de manera enunciativa m&aacute;s no limitadas, cargos por cancelaciones, p&eacute;rdida de vuelos, p&eacute;rdida de equipaje, entre otros.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">&nbsp;</span></p>
                <p class="MsoNormal"><span lang="ES-PE">Los mencionados servicios ser&aacute;n proporcionados por prestadores independientes que no act&uacute;an por o en representaci&oacute;n de &ldquo;PERU ANDES TOP&rdquo;, y en este acto, EL CLIENTE se hace expresamente conocedor de esta situaci&oacute;n, as&iacute; mismo acepta que ni &ldquo;PERU ANDES TOP&rdquo;, ni sus subsidiarias, filiales, controladoras o representantes tienen injerencia alguna en la presentaci&oacute;n de los servicios que ha contratado.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">&nbsp;</span></p>
                <p class="MsoNormal"><span lang="ES-PE">En este acto EL CLIENTE libera a &ldquo;PERU ANDES TOP&rdquo;, as&iacute; como a sus accionistas, consejeros, afiliadas, subsidiarias, asesores, factores, dependientes, o partes relacionadas, de todo tipo de responsabilidad generada con motivo de cualquier incumplimiento, hecho, acto omisi&oacute;n, accidente o lesi&oacute;n vinculada y/o derivada de los servicios que ha contratado EL CLIENTE, incluyendo da&ntilde;os y perjuicios, ya sean directos, indirectos, incidentales, econ&oacute;micos, y/o negligentes, as&iacute; como p&eacute;rdidas, costos o gastos que pudieren ser generados con motivo o en relaci&oacute;n a los servicios contratados a trav&eacute;s de &ldquo;PERU ANDES TOP&rdquo;.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">&nbsp;</span></p>
                <p class="MsoNormal"><span lang="ES-PE">Toda reservaci&oacute;n de hotel, paquetes, vuelos, expedici&oacute;n de boletos, traslados, gu&iacute;as y dem&aacute;s son no reembolsables. Para reservar los paquetes, en su mayor&iacute;a se requiere de un dep&oacute;sito que puede variar de acuerdo con el operador, destino, o temporada en que se quiere viajar.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">&nbsp;</span></p>
                <p class="MsoNormal"><span lang="ES-PE">Los dep&oacute;sitos no son reembolsables en caso de cualquier cancelaci&oacute;n, seg&uacute;n pol&iacute;ticas del operador responsable.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">&nbsp;</span></p>
                <p class="MsoNormal"><span lang="ES-PE">Los boletos de avi&oacute;n de cualquier categor&iacute;a ofrecidos por la empresa son:</span></p>
                <p class="MsoNormal"><span lang="ES-PE">&nbsp;</span></p>
                <p class="MsoNormal"><span lang="ES-PE">No reembolsables.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">No endosables.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">No transferibles (esto quiere decir que no se aceptan cambios de nombres).</span></p>
                <p class="MsoNormal"><span lang="ES-PE">Todas las aerol&iacute;neas se reservan el derecho de sobrevender, cambiar horarios, e incluso cancelar o realizar cambios que ellos consideren pertinentes sin previo aviso y sin responsabilidad de &ldquo;PERU ANDES TOP&rdquo;; esto est&aacute; autorizado gubernamentalmente.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">&nbsp;</span></p>
                <p class="MsoNormal"><span lang="ES-PE">As&iacute; mismo, todas las l&iacute;neas a&eacute;reas y navieras por medidas de seguridad tienen restricciones diferentes para que viajen menores de 18 a&ntilde;os, mujeres embarazadas y personas que utilicen bast&oacute;n o silla de ruedas; por lo que EL CLIENTE acepta que es su responsabilidad consultar las restricciones aplicables a cada l&iacute;nea a&eacute;rea o naviera. EL CLIENTE acepta que &ldquo;PERU ANDES TOP&rdquo;, no es responsable de estas restricciones.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">&nbsp;</span></p>
                <p class="MsoNormal"><span lang="ES-PE">Todos los viajeros deber&aacute;n contar con la documentaci&oacute;n necesaria para realizar su viaje; pasaportes vigentes, visas, siendo de su total responsabilidad los problemas e inconvenientes que puedan surgir por incumplimientos de este requerimiento.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">&nbsp;</span></p>
                <p class="MsoNormal"><span lang="ES-PE">Los cambios o cancelaci&oacute;n de los viajes ocasionados por causas originadas por huracanes, ciclones, terremotos o cualquier otra, son ajenos a &ldquo;PERU ANDES TOP&rdquo;, y quedar&aacute;n sujetos a las pol&iacute;ticas y lineamientos de la l&iacute;nea a&eacute;rea, transportista u operador para la cancelaci&oacute;n total de viaje o cambios de itinerario. Los reembolsos parciales o totales depender&aacute;n de la l&iacute;nea a&eacute;rea, transportista u operador.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">&nbsp;</span></p>
                <p class="MsoNormal"><span lang="ES-PE">El CLIENTE acepta que para realizar cualquier tr&aacute;mite o aclaraci&oacute;n deber&aacute; presentar el ticket de compra y/o factura, y la nota de pedido que contiene los datos de su viaje. As&iacute; mismo EL CLIENTE acepta que la(s) persona(s) que realizan la contrataci&oacute;n de los servicios son las personas que firman y aceptan la hoja de condiciones generales y la(s) &uacute;nica(s) facultada(s) para realizar las aclaraciones o reclamaciones.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">&nbsp;</span></p>
                <p class="MsoNormal"><span lang="ES-PE">El CLIENTE /USUARIO ser&aacute; responsable de la autenticidad de la informaci&oacute;n facilitada al sistema para la realizaci&oacute;n de la reserva, y especialmente de la veracidad de los datos referentes a tarjetas de cr&eacute;dito.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">El CLIENTE /USUARIO ser&aacute; responsable de la direcci&oacute;n de correo electr&oacute;nico y/o otras formas de contacto, que ser&aacute; tenida a todos los efectos como veraz para cualquier tipo de notificaci&oacute;n.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">&nbsp;</span></p>
                <p class="MsoNormal"><span lang="ES-PE">La informaci&oacute;n contenida en esta web puede contener errores de transcripci&oacute;n, traducci&oacute;n, y/o erratas de cualquier otro tipo, aver&iacute;as inform&aacute;ticas, de funcionamiento, y/o similares, por los que no se aceptar&aacute; responsabilidad alguna.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">&nbsp;</span></p>
                <p class="MsoNormal"><span lang="ES-PE">En el momento de confirmaci&oacute;n de la reserva se le solicitar&aacute; que acepte estas condiciones generales, que se entender&aacute; como las &uacute;nicas v&aacute;lidas, quedando sujeta a ellas cualquier reserva y/o modificaci&oacute;n de la misma.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">&nbsp;</span></p>
                <p class="MsoNormal"><span lang="ES-PE">CAUSALES DE RESCISI&Oacute;N Y CONSECUENCIAS JUR&Iacute;DICAS:</span></p>
                <p class="MsoNormal"><span lang="ES-PE">&nbsp;</span></p>
                <p class="MsoNormal"><span lang="ES-PE">El fundamento legal se encuentra acorde a lo establecido por la (legislaci&oacute;n peruana), esto para garantizar, transparentar, informar y orientar correctamente a EL CLIENTE.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">&nbsp;</span></p>
                <p class="MsoNormal"><span lang="ES-PE">EL CLIENTE acepta por falta de pago total o parcial de los servicios que ha contratado a trav&eacute;s de &ldquo;PERU ANDES TOP&rdquo; ser&aacute; causa suficiente de cancelaci&oacute;n o rescisi&oacute;n del contrato y de los servicios contratados por EL CLIENTE con los diversos prestadores mencionados que pudieran ser de manera enunciativa m&aacute;s no limitativa: l&iacute;neas a&eacute;reas, hoteles, transportistas terrestres, mar&iacute;timos u operadores, etc. por lo que en este acto EL CLIENTE libera en todo momento a &ldquo;PERU ANDES TOP&rdquo;, a sus accionistas, consejeros, afiliadas, subsidiarias, asesores, factores dependientes o partes relacionadas de cualquier responsabilidad que por su incumplimiento (DEL CLIENTE) pudiera corresponder.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">&nbsp;</span></p>
                <p class="MsoNormal"><span lang="ES-PE">Los precios que ofrece &ldquo;PERU ANDES TOP E.I.R.L, no incluyen los siguientes conceptos:</span></p>
                <p class="MsoNormal"><span lang="ES-PE">&nbsp;</span></p>
                <p class="MsoNormal"><span lang="ES-PE">Gastos de visado de entrada a cualquier pa&iacute;s.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">Gastos de tramitaci&oacute;n de pasaportes.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">Propinas de tipo personal a cualquier empleado ajeno a &ldquo;PERU ANDES TOP&rdquo;</span></p>
                <p class="MsoNormal"><span lang="ES-PE">En paquetes: Traslados a sitios diferentes de los que se encuentran especificados en el itinerario.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">Exceso de equipaje.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">Gastos extras de ning&uacute;n tipo que no est&eacute;n debidamente especificados en los itinerarios.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">POL&Iacute;TICAS DE RESERVACI&Oacute;N:</span></p>
                <p class="MsoNormal"><span lang="ES-PE">&nbsp;</span></p>
                <p class="MsoNormal"><span lang="ES-PE">Las tarifas que aplican son v&aacute;lidas al momento de la cotizaci&oacute;n, para asegurar la tarifa cotizada, se debe generar el apartado o dep&oacute;sito completo del servicio. De lo contrario, puede existir variaci&oacute;n por cambio de disponibilidad o tipo de cambio. La reserva ser&aacute; v&aacute;lida &uacute;nicamente cuando un experto en ventas confirme el servicio por alguno de nuestros canales oficiales.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">Su n&uacute;mero de confirmaci&oacute;n le ser&aacute; enviado despu&eacute;s de que haya efectuado el pago de su reservaci&oacute;n, (anticipo o pago total). Hasta ese momento se considera una reservaci&oacute;n confirmada.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">Las reservaciones de los servicios est&aacute;n sujetas a disponibilidad al momento de procesar su solicitud y no podr&aacute;n ser garantizadas hasta haber recibido el pago total.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">En las reservaciones de hoteles y paquetes terrestres, antes de solicitar el pago, verificaremos disponibilidad con el proveedor; por lo que le enviaremos la confirmaci&oacute;n dentro de las siguientes 24 horas.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">El pago de los servicios se efectuar&aacute; directamente por el cliente, una vez establecida la relaci&oacute;n comercial con &ldquo;PERU ANDES TOP&rdquo;.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">Posterior a la reservaci&oacute;n y confirmaci&oacute;n, el cliente deber&aacute; imprimir el cup&oacute;n correspondiente y presentarlo al momento de que haga el check in.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">El cliente deber&aacute; leer las pol&iacute;ticas de cancelaci&oacute;n, ya que cualquier cambio de reservaci&oacute;n est&aacute; sujeto a disponibilidad y re-cotizaci&oacute;n de tarifas y a las pol&iacute;ticas del prestador de servicios o l&iacute;nea a&eacute;rea. Deber&aacute; tener a la mano su n&uacute;mero de reservaci&oacute;n y contactar al &aacute;rea correspondiente de la empresa para cualquier aclaraci&oacute;n.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">Los precios son por persona e incluyen los servicios que se indican en la descripci&oacute;n.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">POL&Iacute;TICAS DE PAGO:</span></p>
                <p class="MsoNormal"><span lang="ES-PE">&nbsp;</span></p>
                <p class="MsoNormal"><span lang="ES-PE">El monto total de su reservaci&oacute;n, o el anticipo, pueden ser pagados mediante transferencia bancaria, pago en efectivo en sucursal o cargo a tarjeta, previa confirmaci&oacute;n de la disponibilidad de los servicios.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">Aceptamos las siguientes tarjetas de cr&eacute;dito: Visa, MasterCard y American Express. El personal de la empresa con gusto le proporcionar&aacute; los datos de las comisiones bancarias que aplican, as&iacute; como los cargos bancarios en pagos diferidos.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">Las tarifas publicadas en nuestro sitio est&aacute;n cotizadas en d&oacute;lares americanos (USD). En otros tipos de moneda el monto de la transacci&oacute;n ser&aacute; convertido a d&oacute;lares Americanos USD al tipo de cambio vigente en la fecha de la transacci&oacute;n. Si existe alguna diferencia por la fluctuaci&oacute;n internacional o comisiones bancarias &ldquo;PERU ANDES TOP&rdquo; no es responsable de estas fluctuaciones.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">Si el cliente requiere factura, podr&aacute; solicitarla a trav&eacute;s del enlace enviado en el recibo de pago. &Uacute;nicamente se podr&aacute; hacer la factura en el mismo mes que se contrata el servicio</span></p>
                <p class="MsoNormal"><span lang="ES-PE">POL&Iacute;TICAS DE CANCELACI&Oacute;N:</span></p>
                <p class="MsoNormal"><span lang="ES-PE">&nbsp;</span></p>
                <p class="MsoNormal"><span lang="ES-PE">Las cancelaciones deber&aacute;n ser informadas al personal de la empresa que lo est&eacute; atendiendo por escrito a trav&eacute;s de correo electr&oacute;nico. Las pol&iacute;ticas de cancelaci&oacute;n var&iacute;an de acuerdo con el servicio contratado. &ldquo;PERU ANDES TOP&rdquo; act&uacute;a como intermediario entre el usuario y el prestador del servicio.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">PARA HOTELES:</span></p>
                <p class="MsoNormal"><span lang="ES-PE">&nbsp;</span></p>
                <p class="MsoNormal"><span lang="ES-PE">Las pol&iacute;ticas de cancelaci&oacute;n de los hoteles son espec&iacute;ficas para cada hotel por lo que al momento de que usted elija el hotel podr&aacute; solicitar al personal de empresa las pol&iacute;ticas de cancelaci&oacute;n que apliquen en su caso.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">Los precios de los hoteles son por habitaci&oacute;n con el r&eacute;gimen de comidas que haya solicitado.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">En paquetes donde se incluye alojamiento, en caso de existir alg&uacute;n problema de disponibilidad, se efectuar&aacute; cambio en los hoteles elegidos y el o los hotel(es) que se reemplacen ser&aacute;n de categor&iacute;a similar y dicho cambio ser&aacute; comunicado con la debida antelaci&oacute;n.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">La hora de ingreso es a partir de las 15:00 hrs. del d&iacute;a contratado y finaliza a las 10:00 horas del &uacute;ltimo d&iacute;a fijado para la partida, en caso de llegar antes de las 15:00 horas es posible que su habitaci&oacute;n no le sea otorgada en ese momento. Si requiere prolongar su estancia despu&eacute;s de la hora de salida deber&aacute; notificarlo a la recepci&oacute;n y solicitar directamente con el hotel la estancia adicional.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">PARA TRANSPORTACI&Oacute;N TERRESTRE Y/O TOURS:</span></p>
                <p class="MsoNormal"><span lang="ES-PE">&nbsp;</span></p>
                <p class="MsoNormal"><span lang="ES-PE">Ser&aacute;n considerados como datos personales sensibles aquellos as&iacute; dispuestos por la Ley Federal de Protecci&oacute;n de Datos en Posesi&oacute;n de los Particulares, que de forma enunciativa m&aacute;s no limitativa, son los datos que forman parte de la intimidad del personal y cuya divulgaci&oacute;n pone en riesgo o da origen a discriminaci&oacute;n por aspectos de origen racial o &eacute;tnico, estado de salud, informaci&oacute;n gen&eacute;tica, creencias religiosas, filos&oacute;ficas o morales, afiliaci&oacute;n sindical, opiniones pol&iacute;ticas y preferencias sexuales.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">&nbsp;</span></p>
                <p class="MsoNormal"><span lang="ES-PE">FINALIDADES DEL TRATAMIENTO DE SUS DATOS PERSONALES.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">&nbsp;</span></p>
                <p class="MsoNormal"><span lang="ES-PE">Las pol&iacute;ticas de cancelaci&oacute;n de los tours y transportaci&oacute;n terrestre son espec&iacute;ficas para cada servicio por lo que al momento de que usted elija el tipo de traslado o tour podr&aacute; solicitar al personal de la empresa, las pol&iacute;ticas de cancelaci&oacute;n de cada uno. No obstante, lo anterior, a continuaci&oacute;n, le describimos, de manera enunciativa, m&aacute;s no limitativa, los cargos por cancelaci&oacute;n aplicables en transportaci&oacute;n terrestre y/o tours:</span></p>
                <p class="MsoNormal"><span lang="ES-PE">&ndash; o Reservaciones canceladas antes de la fecha del servicio est&aacute;n sujetas a cargo sobre el monto total de la cantidad de su reservaci&oacute;n, dependiendo de las pol&iacute;ticas del prestador del servicio.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">&nbsp;</span></p>
                <p class="MsoNormal"><span lang="ES-PE">&ndash; o Reservaciones canceladas antes de la fecha del servicio o en caso de no presentarse a tomar los servicios, no ser&aacute;n reembolsables.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">&nbsp;</span></p>
                <p class="MsoNormal"><span lang="ES-PE">En los paquetes ofrecidos, la Agencia de Viajes y las compa&ntilde;&iacute;as prestatarias se reservan el derecho de modificar el itinerario de viaje o de los hoteles previstos s&oacute;lo en caso de que fuera imprescindible para una mejor organizaci&oacute;n de este o si existen circunstancias de fuerza mayor que lo obliguen.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">La Agencia de Viajes act&uacute;a como intermediaria y no ser&aacute; responsable de los retrasos, adelantos o cancelaciones en los itinerarios de las compa&ntilde;&iacute;as a&eacute;reas o de las empresas transportistas, siendo los gastos que se originen a cargo del cliente.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">SERVICIOS A&Eacute;REOS</span></p>
                <p class="MsoNormal"><span lang="ES-PE">&nbsp;</span></p>
                <p class="MsoNormal"><span lang="ES-PE">Las tasas de aeropuerto no est&aacute;n incluidas en los paquetes.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">Las tarifas a&eacute;reas son por persona, puede o no incluir los impuestos. Se especificar&aacute; al momento de realizar su compra.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">Pol&iacute;ticas de cancelaci&oacute;n y penalizaci&oacute;n por cambios de fecha entrar&aacute;n en vigor al momento de que los boletos sean emitidos y var&iacute;an dependiendo de la l&iacute;nea a&eacute;rea que realice el traslado. No importa la anticipaci&oacute;n con la que se realice el cambio o la cancelaci&oacute;n, en todo caso se deber&aacute; consultar con la l&iacute;nea a&eacute;rea correspondiente.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">CANCELACI&Oacute;N POR CAUSAS NO IMPUTABLES A LA EMPRESA:</span></p>
                <p class="MsoNormal"><span lang="ES-PE">&nbsp;</span></p>
                <p class="MsoNormal"><span lang="ES-PE">&ldquo;PERU ANDES TOP&rdquo; act&uacute;a como agente intermediario entre el cliente y el prestador de los bienes y servicios que se publican en el sitio www.gettripvacation.com, los servicios que se promueven son: hospedaje de hoteles, transportaci&oacute;n terrestre y tours, para lo cual &ldquo;PERU ANDES TOP&rdquo; establece negociaciones comerciales con proveedores calificados y de con amplia reputaci&oacute;n el mercado; no obstante lo anterior &ldquo;PERU ANDES TOP&rdquo; no puede asumir ninguna responsabilidad con quienes compran servicios en la p&aacute;gina www.peruandestop.com por actos u omisiones en los servicios de esos proveedores, ya que &ldquo;PERU ANDES TOP&rdquo; no tiene representaci&oacute;n legal ni control administrativo sobre los bienes, procedimientos, personal y equipo de esos proveedores.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">&ldquo;PERU ANDES TOP&rdquo; no asumir&aacute; responsabilidad por ninguna reclamaci&oacute;n, costo o gastos que surjan por heridas personales o de terceras personas, accidentes o deceso, p&eacute;rdida o da&ntilde;os de pertenencias personales, p&eacute;rdida de diversi&oacute;n, enojo, desilusi&oacute;n, angustia o frustraci&oacute;n ya sea mental o f&iacute;sica que resulte de lo que a continuaci&oacute;n se menciona:</span></p>
                <p class="MsoNormal"><span lang="ES-PE">Actos u omisiones de cualquiera otra persona que no sean empleados de &ldquo;PERU ANDES TOP&rdquo;</span></p>
                <p class="MsoNormal"><span lang="ES-PE">Enfermedad, robo, disputas laborales, fallas mec&aacute;nicas, cuarentena, acciones gubernamentales, clima, desastres naturales o cualquier otra causa ajena al control directo de &ldquo;PERU ANDES TOP&rdquo;.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">Incumplimiento del cliente en obtener la documentaci&oacute;n requerida para su viaje como: pasaportes, visas y certificados o cualquier documento que es su responsabilidad tramitar, en ese caso usted no tendr&aacute; derecho a ning&uacute;n reembolso.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">Omisi&oacute;n de seguimiento de instrucciones por parte del cliente en horarios de salida de aeropuerto, hora y fecha de entrada y salida de hoteles, pol&iacute;tica de canje de cupones.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">Cancelaci&oacute;n o cambio por cualquier motivo de los servicios de viaje ofrecidos. Nos reservamos el derecho de cancelar o cambiar los servicios de viaje a nuestra discreci&oacute;n, pero se tratar&aacute; de sustituirlos con servicios comparables. En caso de cancelaci&oacute;n &ldquo;PERU ANDES TOP&rdquo; tendr&aacute; la responsabilidad de reembolsar el monto total del dinero pagado.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">&ldquo;PERU ANDES TOP&rdquo; mantiene actualizada la base de datos de sus proveedores respecto a precios y condiciones de los servicios, no obstante lo anterior existe la posibilidad de que los proveedores realicen modificaciones o proporcionen informaci&oacute;n err&oacute;nea respecto a la vigencia de algunas tarifas; en caso de cualquier cambio de tarifa, ya sea menor o mayor, un experto en ventas se pondr&aacute; en contacto con usted para informarle esta modificaci&oacute;n y que usted est&eacute; en libertad de aceptar o no, la situaci&oacute;n que se presente respecto de la reservaci&oacute;n que realiz&oacute;, no omitimos mencionar que &ldquo;PERU ANDES TOP&rdquo; se deslinda expresamente y a sus proveedores de cualquier responsabilidad o pago de indemnizaci&oacute;n por esa cancelaci&oacute;n.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">Las fotograf&iacute;as mostradas en el portal son representativas y no garantiza que a su llegada todo sea exactamente igual como aqu&iacute; se puede ver.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">La categor&iacute;a de las estrellas asignada a los hoteles y servicios, est&aacute;n basados en la interpretaci&oacute;n de &ldquo;PERU ANDES TOP&rdquo; y puede diferir de las categor&iacute;as reportadas en otros lugares.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">La descripci&oacute;n de los servicios de viaje es informativa y no garantizan que ser&aacute;n exactamente iguales a su llegada.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">Cualquier reclamaci&oacute;n deber&aacute; hacerse por escrito al correo electr&oacute;nico al personal de la empresa debiendo ser recibida a m&aacute;s tardar 15 d&iacute;as despu&eacute;s del regreso de su viaje. Pasado ese lapso de tiempo la empresa no recibir&aacute; reclamo alguno.</span></p>
                <p class="MsoNormal"><span lang="ES-PE">ATENTAMENTE,</span></p>
                <p class="MsoNormal"><span lang="ES-PE">&nbsp;</span></p>
                <p class="MsoNormal"><span lang="ES-PE">&ldquo;PERU ANDES TOP&rdquo; E.I.R.L.</span></p>',
                'finaltitle' => 'here'
            ]
            // Agrega más datos si es necesario
        ]);

    }
}
